# Generated by Django 5.2.17 on 2026-10-01 14:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        ('practitioners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('debut', models.DateTimeField(db_index=True, verbose_name='Début')),
                ('fin', models.DateTimeField(verbose_name='Fin')),
                ('statut', models.CharField(choices=[('pending', 'En attente de confirmation'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Terminé'), ('no_show', 'Patient absent')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('prix_xof', models.PositiveIntegerField(help_text='Prix figé à la création du rendez-vous.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix (XOF)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('motif_annulation', models.TextField(blank=True, default='', verbose_name="Motif d'annulation")),
                ('confirme_le', models.DateTimeField(blank=True, null=True, verbose_name='Confirmé le')),
                ('annule_le', models.DateTimeField(blank=True, null=True, verbose_name='Annulé le')),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_annules', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
                ('praticien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous', to='practitioners.practitioner', verbose_name='Praticien')),
                ('soin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous', to='catalog.soin', verbose_name='Soin')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ('-debut',),
                'indexes': [models.Index(fields=['praticien', 'debut'], name='rdv_praticien_debut_idx'), models.Index(fields=['patient', 'debut'], name='rdv_patient_debut_idx'), models.Index(fields=['statut', 'debut'], name='rdv_statut_debut_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fin__gt', models.F('debut'))), name='rdv_fin_apres_debut'), models.UniqueConstraint(condition=models.Q(('statut', 'cancelled'), _negated=True), fields=('praticien', 'debut'), name='rdv_praticien_debut_unique_actif')],
            },
        ),
        # Contrainte d'exclusion PostgreSQL : deux rendez-vous actifs ne
        # peuvent pas se chevaucher pour un même praticien. Écrit en SQL brut
        # car Django 5.2 n'expose pas encore `ExclusionConstraint`.
        migrations.RunSQL(
            sql="""
                ALTER TABLE appointments_appointment
                ADD CONSTRAINT appointments_rdv_pas_de_double_reservation
                EXCLUDE USING gist (
                    praticien_id WITH =,
                    tstzrange(debut, fin, '[)') WITH &&
                )
                WHERE (statut <> 'cancelled');
            """,
            reverse_sql="""
                ALTER TABLE appointments_appointment
                DROP CONSTRAINT IF EXISTS appointments_rdv_pas_de_double_reservation;
            """,
        ),
    ]
