# Generated by Django 5.2.17 on 2026-10-01 13:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du cabinet')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('ville', models.CharField(default='Dakar', max_length=80, verbose_name='Ville')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('actif', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Cabinet',
                'verbose_name_plural': 'Cabinets',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('biographie', models.TextField(blank=True, default='', verbose_name='Biographie')),
                ('annees_experience', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(80)], verbose_name="Années d'expérience")),
                ('numero_ordre', models.CharField(blank=True, default='', max_length=50, verbose_name="Numéro d'ordre")),
                ('actif', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='praticiens', to='practitioners.cabinet', verbose_name='Cabinet')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'dentiste'}, on_delete=django.db.models.deletion.CASCADE, related_name='praticien', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('specialites', models.ManyToManyField(blank=True, related_name='praticiens', to='practitioners.specialite', verbose_name='Spécialités')),
            ],
            options={
                'verbose_name': 'Praticien',
                'verbose_name_plural': 'Praticiens',
                'ordering': ('user__nom',),
                'indexes': [models.Index(fields=['actif', 'user'], name='praticien_actif_user_idx')],
            },
        ),
    ]
