# Generated by Django 5.2.17 on 2026-10-01 14:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practitioners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionDisponibilite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(blank=True, null=True, verbose_name='Heure de début (vide = toute la journée)')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin (vide = toute la journée)')),
                ('type', models.CharField(choices=[('conge', 'Congé'), ('fermeture', 'Fermeture'), ('rdv_professionnel', 'Rendez-vous professionnel'), ('autre', 'Autre')], default='conge', max_length=30, verbose_name='Type')),
                ('motif', models.TextField(blank=True, default='', verbose_name='Motif')),
                ('praticien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='practitioners.practitioner', verbose_name='Praticien')),
            ],
            options={
                'verbose_name': 'Exception de disponibilité',
                'verbose_name_plural': 'Exceptions de disponibilité',
                'ordering': ('date', 'heure_debut'),
                'indexes': [models.Index(fields=['praticien', 'date'], name='exception_praticien_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('heure_debut__isnull', True), ('heure_fin__isnull', True)), models.Q(('heure_debut__isnull', False), ('heure_fin__gt', models.F('heure_debut')), ('heure_fin__isnull', False)), _connector='OR'), name='exception_horaires_coherents')],
            },
        ),
        migrations.CreateModel(
            name='HoraireHebdomadaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('jour', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='0 = lundi ... 6 = dimanche.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Jour de la semaine')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('actif', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('praticien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='practitioners.practitioner', verbose_name='Praticien')),
            ],
            options={
                'verbose_name': 'Horaire hebdomadaire',
                'verbose_name_plural': 'Horaires hebdomadaires',
                'ordering': ('jour', 'heure_debut'),
                'indexes': [models.Index(fields=['praticien', 'jour', 'actif'], name='horaire_praticien_jour_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('heure_fin__gt', models.F('heure_debut'))), name='horaire_fin_apres_debut'), models.UniqueConstraint(fields=('praticien', 'jour', 'heure_debut'), name='unique_horaire_par_jour')],
            },
        ),
    ]
