# Generated by Django 5.2.17 on 2026-10-01 13:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practitioners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieSoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie de soin',
                'verbose_name_plural': 'Catégories de soins',
                'ordering': ('ordre', 'nom'),
            },
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du soin')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('duree_minutes', models.PositiveIntegerField(default=30, help_text='Durée du rendez-vous, en minutes.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)], verbose_name='Durée (minutes)')),
                ('prix_xof', models.PositiveIntegerField(help_text='Montant en francs CFA (entier, jamais de flottant).', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix (XOF)')),
                ('actif', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soins', to='catalog.categoriesoin', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Soin',
                'verbose_name_plural': 'Soins',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='SoinPraticien',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('prix_xof', models.PositiveIntegerField(blank=True, help_text='Laissez vide pour utiliser le prix du catalogue.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix spécifique (XOF)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('praticien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins_proposes', to='practitioners.practitioner', verbose_name='Praticien')),
                ('soin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='par_praticiens', to='catalog.soin', verbose_name='Soin')),
            ],
            options={
                'verbose_name': 'Soin proposé',
                'verbose_name_plural': 'Soins proposés',
                'ordering': ('soin__nom',),
            },
        ),
        migrations.AddIndex(
            model_name='soin',
            index=models.Index(fields=['actif', 'nom'], name='soin_actif_nom_idx'),
        ),
        migrations.AddConstraint(
            model_name='soin',
            constraint=models.CheckConstraint(condition=models.Q(('prix_xof__gte', 0)), name='soin_prix_xof_positif'),
        ),
        migrations.AddConstraint(
            model_name='soin',
            constraint=models.CheckConstraint(condition=models.Q(('duree_minutes__gte', 5)), name='soin_duree_minimum_5'),
        ),
        migrations.AddConstraint(
            model_name='soinpraticien',
            constraint=models.UniqueConstraint(fields=('praticien', 'soin'), name='unique_soin_par_praticien'),
        ),
    ]
