# Generated by Django 5.2.17 on 2026-10-01 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('type', models.CharField(choices=[('appointment_created', 'Demande de rendez-vous'), ('appointment_confirmed', 'Rendez-vous confirmé'), ('appointment_cancelled', 'Rendez-vous annulé'), ('appointment_no_show', 'Patient absent'), ('appointment_reminder', 'Rappel de rendez-vous')], db_index=True, max_length=30, verbose_name='Type')),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=20, verbose_name='Canal')),
                ('sujet', models.CharField(max_length=255, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyée'), ('failed', 'Échec')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('lue', models.BooleanField(db_index=True, default=False, verbose_name='Lue')),
                ('envoi_le', models.DateTimeField(blank=True, null=True, verbose_name='Envoyée le')),
                ('erreur', models.TextField(blank=True, default='', verbose_name='Erreur')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appointments.appointment', verbose_name='Rendez-vous')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['destinataire', 'created_at'], name='notif_destinataire_date_idx'), models.Index(fields=['statut', 'created_at'], name='notif_statut_date_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('rendez_vous__isnull', False)), fields=('rendez_vous', 'type', 'canal'), name='notif_unique_rdv_type_canal')],
            },
        ),
    ]
